#!/bin/bash

# Add libvirt configuration to nsswitch.conf
cat > /etc/nsswitch.conf << "EOF"
# /etc/nsswitch.conf
#
# Example configuration of GNU Name Service Switch functionality.
# If you have the `glibc-doc-reference' and `info' packages installed, try:
# `info libc "Name Service Switch"' for information about this file.

passwd:         files systemd sss
group:          files systemd sss
shadow:         files systemd sss
gshadow:        files systemd

hosts:          files mdns4_minimal [NOTFOUND=return] libvirt dns myhostname
networks:       files

protocols:      db files
services:       db files sss
ethers:         db files
rpc:            db files

netgroup:       nis sss
automount:  sss
EOF

# Make /var/lib/libvirt/dnsmasq to show where expected by libnss_libvirt
ln -s /var/lib/snapd/hostfs/var/lib/libvirt/dnsmasq/ /var/lib/libvirt/
